# authentik-db.yaml

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
