apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret-key
  namespace: authentik
type: Opaque
stringData:
  secret_key: "nbcJTh7uNOmWaAPHIPG3/omQR9K5REHsYZkv13HN/A0ITIBBUozgiZDHLTbC7iVWzkfvXWLxbunwoUrh"

