infisical:
  enabled: true
  replicaCount: 1
  autoDatabaseSchemaMigration: true
  kubeSecretRef: infisical-secrets
  revisionHistoryLimit: 0
postgresql:
  enabled: false
redis:
  enabled: true
ingress:
  enabled: false
ingress-nginx:
  enabled: false
