apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  oidc.authentik.clientSecret: "2mRi6xdJzA9GoymDdKOVlDOPtjYwPala9BBQDdFVuMkPZIdHgTgKuPViljBTZ9IC5QT6ONAwTkdwjZeWey5YmRaGz5OPVe8oHfh8jFNxkxNkrMT3FdsBtYuzU3cMwo9e"
