apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: n8n
spec:
  instances: 2
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: app
      owner: app
