apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-store
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            secretRef:
              name: infisical-credentials
              namespace: external-secrets
              key: clientId
          clientSecret:
            secretRef:
              name: infisical-credentials
              namespace: external-secrets
              key: clientSecret
      hostAPI: https://infisical.pukarsubedi.com/api
