apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-db
  namespace: infisical
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 5Gi
  bootstrap:
    initdb:
      database: infisical
      owner: infisical
