apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  destination:
    namespace: ollama
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: ''
      kind: PersistentVolumeClaim
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
  project: default
  sources:
    - chart: ollama
      helm:
        releaseName: ollama
        valueFiles:
          - $values/dev-cluster/apps/ollama/values.yaml
      repoURL: https://helm.otwld.com/
      targetRevision: 1.63.0
    - ref: values
      repoURL: https://github.com/subedi-labs/homelab-gitops.git
      targetRevision: HEAD
    - path: dev-cluster/apps/ollama
      repoURL: https://github.com/subedi-labs/homelab-gitops.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true