ollama:
  gpu:
    enabled: false

  models:
    pull:
      - llama3.2:3b

persistentVolume:
  enabled: true
  storageClass: longhorn

  size: 15Gi
  accessModes:
    - ReadWriteOnce

service:
  type: ClusterIP
  port: 11434

resources:
  requests:
    cpu: "500m"
    memory: 1Gi
  limits:
    cpu: "3"
    memory: 4Gi

extraEnv:
  - name: OLLAMA_ORIGINS
    value: "https://homebrain.pukarsubedi.com"
  - name: OLLAMA_KEEP_ALIVE
    value: "5m"

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  path: /api/tags
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent

ingress:
  enabled: false
